### ISSUE TITLE
why the extensive permissions requirement ? 

### ISSUE THREAD

**Issue by royharoush** [finalclap/CopyAllUrl_Chrome#3]
the initial permissions where "read browser history" and manage clipboard. 

![image](https://user-images.githubusercontent.com/8113056/42806800-ed3a179a-89b7-11e8-8176-0219fb6038be.png)

either your chrome store account was compromised ... ?

**Comment by webmastir** [comment]
I don't think this is an active project, so I doubt you will get an answer. 

The permissions haven't changed in quite some time. 

http://vincepare.github.io/CopyAllUrl_Chrome/

**Comment by royharoush** [comment]
@webmastir then it looks like someone have compromised the the chrome developer account. 
the permissions were very slim when i started using it. 
this extension has well over 100k users. 
i changed the manifest file myself, but i doubt others have done so as well. 
also left on a comment on the extension page, if there will be no reply i suggest we should start reporting this extension as abusive.
